### ISSUE TITLE
problem using BCR_LCP_GSA to build bwt 

### ISSUE THREAD

**Issue by Kedraous** [giovannarosone/BCR_LCP_GSA#2]
Hello,

I'm trying to use ebwt2InDel to find SNPs in sequencing reads. I'm using the following code to build bwt of my paired end reads.

BCR_LCP_GSA 9_S6_L004_R1_001.fastq.gz 9_S6_R1.fastq.bwt
BCR_LCP_GSA 9_S6_L004_R2_001.fastq.gz) 9_S6_R2.fastq.bwt

I have removed the reads containing N prior to running the job. However, I kept getting an error indicating "The (new and-or old) reads have a different length". And following that, I processed the reads with fastp to make all the reads of equal length, but I'm still getting the same error. I also tried including zcat to unpack the reads, but the same error.

The error;

TIMER start buildBCR User: 3e-06s System: 1.1e-05s Actual: 1.6e-05s Efficiency: 87.5%
The (new and-or old) reads have a different length.
BCR_LCP_GSA: TransposeFasta.cpp:235: bool TransposeFasta::findLengthNseq(const string&, const string&, std::__cxx11::string): Assertion `lengthSeqVector.size() == nSeq' failed.
/var/spool/torque/mom_priv/jobs/29994642.moab.SC: line 15: 38504 Aborted (core dumped) BCR_LCP_GSA <(zcat 9_S6_L004_R1_001_no_N_151.fastq.gz) 9_S6_R1.fastq.bwt

Please help in clarifying if there is something I'm doing wrong

Best regards,
Kedra

**Comment by Kedraous** [comment]
There is a typo and some mistake in the original issue (the bracket is a typo when I write the issue and it was for a different read - before processing to make them of equal length, on which I have tried running BCR_LCP_GSA and got the same error).  below is the correct code. And as already mentioned, I tried without zcat as well.

BCR_LCP_GSA <(zcat 9_S6_L004_R1_001_no_N_151.fastq.gz) 9_S6_R1.fastq.bwt
BCR_LCP_GSA <(zcat 9_S6_L004_R2_001_no_N_151.fastq.gz) 9_S6_R2.fastq.bwt

I have removed the reads containing N prior to running the job. However, I kept getting an error indicating "The (new and-or old) reads have a different length". And following that, I processed the reads with fastp to make all the reads of equal length, but I'm still getting the same error. I also tried including zcat to unpack the reads, but the same error.

The error;

TIMER start buildBCR User: 3e-06s System: 1.1e-05s Actual: 1.6e-05s Efficiency: 87.5%
 The (new and-or old) reads have a different length.
 BCR_LCP_GSA: TransposeFasta.cpp:235: bool TransposeFasta::findLengthNseq(const string&, const string&, std::__cxx11::string): Assertion `lengthSeqVector.size() == nSeq' failed.
 /var/spool/torque/mom_priv/jobs/29994642.moab.SC: line 15: 38504 Aborted (core dumped) BCR_LCP_GSA <(zcat 9_S6_L004_R1_001_no_N_151.fastq.gz) 9_S6_R1.fastq.bwt

**Comment by giovannarosone** [comment]
Actually the sentence 
"The (new and-or old) reads have a different length."
is just information, as BCR works with variable length strings.

About the error:
Assertion `lengthSeqVector.size() == nSeq' failed.
BCR reads the input file twice and appears to get a different number of strings. There must be a problem with the formatting of the original file.


Since the input is "directly" a FASTQ file, you should compile by using "make FASTQ = 1", so that BCR uses the Heng Li library to read the file.

Is the FASTQ file a multi-line file?

**Comment by Kedraous** [comment]
Thanks, will try this out. 
Yes, it is a multi-line FASTQ file

**Comment by Kedraous** [comment]
Thank you so much!
I tried to compile it by using 'make FASTQ = 1' as you suggested and it returned something like there is nothing to do with the file. I then reformatted the reads with reformat.sh from BBMap suite and generated the output in Fasta format. 

I tried running the BCR on the generated fasta and it's currently running, but it's generating a lot of cyc.txt files and other outputs i.e., bwt_0.aux, lcp_0.aux and da_0.aux (repetitively by giving it consecutive number like bwt_1.aux, bwt_2.aux). It has already generated five of each. Is this normal? I am new to this kind of work and it takes me longer to figure things out. So I apologize in advance if it's due to some silly mistakes I'm making.

Could the size of the file be a problem? it's a conifer full genome sequence and I am trying this on read 1 file, which is 57GB.
maximum length of the lines is 151 bases.

**Comment by giovannarosone** [comment]
Yes, it's normal, BCR work to disk in a sequential fashion on "columns" of symbols, so it uses an n cys files, where n is the length of the longest sequence and t partial BWT/LCP/... files, where t is the alphabet size. You can find more details on how BCR works in the paper published on TCS.
If you interrupt the process, you can delete the cyc files using removeCycFile.cpp.
By definition, BCR slows down as reads length increases. It was born for huge short-reads datasets.

**Comment by Kedraous** [comment]
It's all good then. It's completed for one of the reads now and I have three final outputs (ebwt, lcp and da). Thank you so much!

**Comment by giovannarosone** [comment]
Thank you,
note that you can also set different types of output.
