### ISSUE TITLE
Parameters for constructing the eBWT

### ISSUE THREAD

**Issue by ddiazdom** [giovannarosone/BCR_LCP_GSA#3]
Hi,

I am trying to construct the eBWT for big FASTA files (2.6, 12, 24, 36,48, and 57 GBs) using BCR, but it takes too much time. I started with the smallest file, and so far, it has been running for about 10hours. I modified the SIZEBUFFER in the "Parameters.h" file and BUFFERSIZE in "TransposeFasta.h" file, as you mention in the documentation. 

These are the configurations I am using for the 2.6 GB file:

For SIZEBUFFER I used 2690138636 (number of input symbols)
For BUFFERSIZE I used 26635036 (number of DNA symbols over the read length (101 bp))
I also turned off the construction of the other data structures (LCP, DA, posSA). 

A simple solution would be to increase the buffer sizes, but I have the impression I am doing something wrong.

Is there anything else I should modify to speed the computations?

This is what the log says so far:

> 
> BWTCollection: The input is ../ecoli_spades.fasta
> BWTCollection: The output is beetl_test
> Compute the EBWT
> The output format of BCR is at most 5 files (ebwt, lcp, da, posSA, ebwt.qs) - built one after the other.
> BCR uses the external memory for the BWT partial
> BCR of multi-sequences
> Lexicographic order
> dataTypedimAlpha: sizeof(type size of alpha): 1 bytes
> dataTypelenSeq: sizeof(type of seq length): 1 bytes
> dataTypeNSeq: sizeof(type of #sequences): 4 bytes
> dataTypeNChar: sizeof(type of #sequences): 8 bytes
> TIMER start buildBCR User: 8e-06s System: 0s Actual: 1e-05s Efficiency: 80%
> 
> Builds cyc. files and the builds the BCR
> The (new and-or old) reads have the same length.
> Number of sequences reading/writing: 26635036
> Number of characters reading/writing: 2663503600
> In the new collection, we have:
> TrasposeFasta: init buf_ for bases of size 100 * 4527956
> TransposeFasta: The max length (Read) is: 100
> TransposeFasta: Number of reads: 26635036
> TransposeFasta: Total Number of chars (without end-markers): 2663503600
> TransposeFasta: Size Alpha: 5 symbols
> TIMER after TRASP. User: 4e-06s System: 1e-06s Actual: 6e-06s Efficiency: 83.3333%
> Symbols in the input file (ASCII, char, freq, code):
> 35 # 26635036 0
> 65 A 650242090 1
> 67 C 676646070 2
> 71 G 677428806 3
> 84 T 659186634 4
> 
> Start Preprocessing 1611024332 seconds
> End   Preprocessing 1611024353 seconds
> Preprocessing tooks 21 seconds
> 
> SizeAlpha: 5
> Length of the longest sequence: 100
> 
> Number of sequences: 26635036
> Total symbols (without end-markers): 2663503600
> Total symbols (with end-markers) in ebwt: 2690138636
>         - RAM for BCR for computing without considering I/O buffers and including the BWTs partial in internal memory (if set) is at most: 838.238 MebiByte (MiB).
>         - Size buffer in BCR 2.69014e+09 bytes for each buffer.
>         - BCR needs at least 1 bytes * 2690138636 = 2565 MebiByte (MiB) for the I/O buffers.
> 
> Total (max) RAM for BCR for computing eBWT (int/ext) and/or LCP and/or DA and/or SA (including the buffers for reading files): 3403 MebiByte (MiB)

BCR has been at this point most of the running time. htop says it is using 439MB of resident memory.

I would really appreciate it if you can give me some feedback on the matter :)

Kind regards

**Comment by giovannarosone** [comment]
You shouldn't increase the buffer (to read / write files)  ize too much, otherwise you increase the memory swap operations and clearly slow down.
With the default settings, how long does it take?
Are you computing all the data structures?
Your running time are weird, for example BCR can build (with the OUTPUT_FORMAT = 0 option) the BWT of a set with 17.730.496 reads of 100-base in less than 20 minutes.

Anyway, if you want to build more data structures, please set the OUTPUT_FORMAT parameter to 3 (better than 0, if you compute multiple data structures) in the Parameters.h file in order to get separated files.

**Comment by ddiazdom** [comment]
Thanks for your quick reply

> With the default settings, how long does it take?

I haven't tried with default settings yet. I will try now so I can tell you.

> Are` you computing all the data structures?

I just need the eBWT, I tuned off the other data structures in the Parameters.h file

> Your running time are weird, for example BCR can build (with the OUTPUT_FORMAT = 0 option) the BWT of a set with 17.730.496 reads of 100-base in less than 20 minutes.

That's what I thought, that my running time is weird. I am using OUTPUT_FORMAT=0.

**Comment by ddiazdom** [comment]
I reset the buffers to default values, and now it is working properly. When I first modified them, I thought I was setting this parameter: 

> RAM for BCR for computing without considering I/O buffers and including the BWTs partial in internal memory (if set) is at most: 838.238 MebiByte (MiB)

Which, I think, is the working memory buffer for BCR to compute the eBWT. Sorry, my mistake. 

Anyway, is there any parameter I could change to increase this working buffer  (not the I/O buffers)? I need to process big files (>20GB), and I think 838.238 MiB might be too small for a buffer (?)

**Comment by giovannarosone** [comment]
Actually no, there are no particular buffers that are not I/O, since BCR works mainly in external memory.
You may try to change the size of the I/O buffers to find the best trade-off for your computer's architecture.

**Comment by ddiazdom** [comment]
OK, I will try that then. Thank you for your feedback :)
